version: '2.3'
services:
  fhir-server:
    image: hmsdbmitc/hapi-fhir:3.5.0-overlay
    build:
      context: .
      args:
        - HAPI_FHIR_SRC=hapi-fhir-3.x.x
        - HAPI_FHIR_VERSION=3.5.0
        - DBMI_HAPI_FHIR_VERSION=0.2.1
        - HAPI_FHIR_PROFILE=overlay
        - JWT_AUTH_ENABLED=false
    environment:
      DBMI_SSL:
      DBMI_LB:
      DBMI_CREATE_SSL:
      DBMI_PORT: 8082
      DBMI_PARAMETER_STORE_PREFIX:
      DBMI_PARAMETER_STORE_PRIORITY:
      DBMI_APP_DOMAIN: localhost
      FHIR_SERVER_NAME: fhir-server
      FHIR_SERVER_URL: http://localhost:8082/baseDstu3
      FHIR_MYSQL_URL: "jdbc:mysql://fhir-database:3306/jpaserver"
      FHIR_MYSQL_USERNAME: "hapi"
      FHIR_MYSQL_PASSWORD: "tmEqWELhq6ThfbrM"
      JWT_ISSUER: https://dbmiauth-local.auth0.com/
      JWT_AUDIENCE: riTKsD6l6tAC5hIcSzF7DFZ1VRh32sqf
      JWT_COOKIE_NAME: DBMI_JWT
      JWT_HEADER_PREFIX: "JWT "
      JWT_AUTHZ_CLAIM: "http://local.authorization.dbmi.hms.harvard.edu"
      JWT_ADMIN_GROUP: "ppm-admin"
      JWT_AUTH_ENABLED: "false"
    ports:
      - 8082:8082
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8082/healthcheck || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
    depends_on:
      fhir-database:
        condition: service_healthy

  fhir-database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "jdw7d93N9fbdawM"
      MYSQL_DATABASE: 'jpaserver'
      MYSQL_USER: 'hapi'
      MYSQL_PASSWORD: 'tmEqWELhq6ThfbrM'
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -uroot -pjdw7d93N9fbdawM
      interval: 15s
      timeout: 5s
      retries: 15
