version: '2.3'
services:
  fhir-server:
    image: hmsdbmitc/ppm-fhir:${HAPI_FHIR_VERSION_MAJOR}.${HAPI_FHIR_VERSION_MINOR}.${HAPI_FHIR_VERSION_PATCH}
    build:
      context: .
      args:
        - DBMI_HAPI_FHIR_VERSION=${DBMI_HAPI_FHIR_VERSION}
        - HAPI_FHIR_VERSION_MAJOR=${HAPI_FHIR_VERSION_MAJOR}
        - HAPI_FHIR_VERSION_MINOR=${HAPI_FHIR_VERSION_MINOR}
        - HAPI_FHIR_VERSION_PATCH=${HAPI_FHIR_VERSION_PATCH}
        - HAPI_FHIR_VERSION=${HAPI_FHIR_VERSION_MAJOR}.${HAPI_FHIR_VERSION_MINOR}.${HAPI_FHIR_VERSION_PATCH}
    environment:
      DBMI_LB:
      DBMI_SSL: ${DBMI_SSL}
      DBMI_CREATE_SSL: 'true'
      DBMI_PORT: ${PORT}
      DBMI_HTTP_PORT: ${HTTP_PORT}
      DBMI_PARAMETER_STORE_PREFIX:
      DBMI_PARAMETER_STORE_PRIORITY:
      DBMI_APP_DOMAIN: localhost
      JWT_ISSUER: https://dbmiauth-local.auth0.com/
      JWT_AUDIENCE: riTKsD6l6tAC5hIcSzF7DFZ1VRh32sqf
      JWT_COOKIE_NAME: DBMI_JWT
      JWT_HEADER_PREFIX: "JWT "
      JWT_AUTHZ_CLAIM: "http://local.authorization.dbmi.hms.harvard.edu"
      JWT_ADMIN_GROUP: "ppm-admin"
      JWT_AUTH_ENABLED: "false"
      SENTRY_DSN:
      DBMI_APP_HEALTHCHECK_PATH: /${FHIR_ROOT}/metadata
      FHIR_SERVER_URL: ${DBMI_SSL}://localhost:${PORT}/${FHIR_ROOT}
      TOKEN_HEADER_PREFIX: "Bearer "
      AUTHORIZED_TOKENS: abc123abc123,abcdefghijklmnopqrstuvwxyz

      # These are found by HapiProperties.class and used to override set values
      # in hapi.properties
      FHIR_ROOT: ${FHIR_ROOT}
      FHIR_VERSION: ${FHIR_VERSION}
      HAPI_FHIR_OVERLAY: ${HAPI_FHIR_OVERLAY}
      HAPI_DATASOURCE_DRIVER: ${DBMI_DB_DRIVER}
      HAPI_DATASOURCE_URL: "jdbc:mysql://fhir-database:3306/${DBMI_DB_DATABASE}"
      HAPI_DATASOURCE_USERNAME: ${DBMI_DB_USERNAME}
      HAPI_DATASOURCE_PASSWORD: ${DBMI_DB_PASSWORD}
      HAPI_SERVER_ADDRESS: ${DBMI_SSL}://localhost:${PORT}/${FHIR_ROOT}
      HAPI_AUTH: ${HAPI_AUTH}

    ports:
      - ${PORT}:${PORT}
      - ${HTTP_PORT}:${HTTP_PORT}
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --no-check-certificate --tries=1 --spider ${DBMI_SSL}://localhost:${PORT}/${FHIR_ROOT}/metadata || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
    depends_on:
      fhir-database:
        condition: service_healthy

  fhir-database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DBMI_DB_ROOT}
      MYSQL_DATABASE: ${DBMI_DB_DATABASE}
      MYSQL_USER: ${DBMI_DB_USERNAME}
      MYSQL_PASSWORD: ${DBMI_DB_PASSWORD}
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -uroot -p${DBMI_DB_ROOT}
      interval: 15s
      timeout: 5s
      retries: 15
